name:                teatimer
version:             0.1.0.0
github:              "0xmycf/teatimer"
license:             BSD3
author:              "0xmycf"
maintainer:          "mycf.mycf.mycf@gmail.com"
copyright:           "2021 0xmycf"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/0xmycf/teatimer#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  teatimer-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - teatimer
    - split
    - process
